{% set name = "batman" %}
{% set version = "1.9" %}
{% set tag = "1.9-Pennyworth" %}
{% set commit = "b34bb065a1ec7e247d1f1c328bc6ed39c9672c29" %}
{% set sha256 = "15635b53c3fc5725901daffdb425f4ada7aaae0ea721c217b7b7f7a4e1d07743" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://gitlab.com/cerfacs/batman/repository/archive.tar.gz?ref={{ commit }}
  sha256: {{ sha256 }}
  patches:
    - commit.patch

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win]
  number: 2007

requirements:
  host:
    - pip
    - pytest-runner
    - python
    - setuptools
    - scipy >=0.15
    - numpy >=1.13
    - jsonschema
    - pandas >=0.22.0
    - pathos >=0.2
    - paramiko >=2
    - matplotlib-base >=2.1
    - ffmpeg
    - openturns >=1.12
    - scikit-learn >=0.18
    - backports.tempfile  # [py27]
  run:
    - python
    - scipy >=0.15
    - numpy >=1.13
    - jsonschema
    - pandas >=0.22.0
    - pathos >=0.2
    - paramiko >=2
    - matplotlib-base >=2.1
    - ffmpeg
    - openturns >=1.12
    - scikit-learn >=0.18
    - backports.tempfile  # [py27]

test:
  imports:
    - batman
  commands:
    - export MPLBACKEND="Agg"; batman -h

about:
  home: https://gitlab.com/cerfacs/batman
  license: CECILL-B
  license_family: OTHER
  license_file: LICENSE
  summary: 'Bayesian Analysis Tool for Modelling and uncertAinty quaNtification'
  description: |
    Batman is a python module that allows to seamlessly perform statistical
    analysis using any computer solver. From a simple settings file, it handle
    automatically all necessary steps to do such analysis. Furthermore,
    batman's API allows to use independantly all functionalities.
  doc_url: http://batman.readthedocs.io
  dev_url: https://batman-cerfacs.zulipchat.com

extra:
  recipe-maintainers:
    - tupui
    - idast19
