{% set name = "batman" %}
{% set version = "1.7.2" %}
{% set tag = "1.7.2-Lucius" %}
{% set sha256 = "cc13aeb5c027e45234f0eb4c9a7c200a58542224222b490c84590fbc06a96b78" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://gitlab.com/cerfacs/{{ name }}/repository/archive.tar.gz?ref={{ tag }}
  sha256: {{ sha256 }}

build:
  skip: True  # [win]
  number: 3

requirements:
  build:
    - toolchain
    - gcc  # [osx]
    - libgfortran  # [linux]
    - pytest-runner
    - python
    - setuptools
    - scipy >=0.15
    - numpy >=1.13
    - jsonschema
    - pathos >=0.2
    - matplotlib >=2.1
    - ffmpeg
    - openturns ==1.9
    - scikit-learn >=0.18
    - futures  # [py27]
  run:
    - python
    - libgfortran
    - scipy >=0.15
    - numpy >=1.13
    - jsonschema
    - pathos >=0.2
    - matplotlib >=2.1
    - ffmpeg
    - openturns ==1.9
    - scikit-learn >=0.18
    - sphinx >=1.4
    - sphinx_rtd_theme
    - futures  # [py27]

test:
  imports:
    - batman
  commands:
    - batman -h

about:
  home: https://gitlab.com/cerfacs/batman
  license: CECILL-B
  license_family: OTHER
  license_file: LICENSE
  summary: 'Bayesian Analysis Tool for Modelling and uncertAinty quaNtification'
  description: |
    Batman is a python module that allows to seamlessly perform statistical
    analysis using any computer solver. From a simple settings file, it handle
    automatically all necessary steps to do such analysis. Furthermore,
    batman's API allows to use independantly all functionalities.
  doc_url: http://batman.readthedocs.io
  dev_url: https://batman-cerfacs.zulipchat.com

extra:
  recipe-maintainers:
    - tupui
