{% set name = "batman" %}
{% set version = "1.9" %}
{% set tag = "1.9-Pennyworth" %}
{% set sha256 = "a3d57cb8aad4487add0c3d7f915501a88195b6b59c96cbffaf10879cdecd9af7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://gitlab.com/cerfacs/batman/repository/archive.tar.gz?ref={{ tag }}
  sha256: {{ sha256 }}
  patches:
    - commit.patch

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win]
  number: 1000

requirements:
  build:
    - pip
    - pytest-runner
    - python
    - setuptools
    - scipy >=0.15
    - numpy >=1.13
    - jsonschema
    - pandas >=0.22.0
    - pathos >=0.2
    - paramiko >=2
    - matplotlib >=2.1
    - ffmpeg
    - openturns >=1.10
    - scikit-learn >=0.18
    - backports.tempfile  # [py27]
  run:
    - python
    - scipy >=0.15
    - numpy >=1.13
    - jsonschema
    - pandas >=0.22.0
    - pathos >=0.2
    - paramiko >=2
    - matplotlib >=2.1
    - ffmpeg
    - openturns >=1.10
    - scikit-learn >=0.18
    - backports.tempfile  # [py27]

test:
  imports:
    - batman
  commands:
    - batman -h

about:
  home: https://gitlab.com/cerfacs/batman
  license: CECILL-B
  license_family: OTHER
  license_file: LICENSE
  summary: 'Bayesian Analysis Tool for Modelling and uncertAinty quaNtification'
  description: |
    Batman is a python module that allows to seamlessly perform statistical
    analysis using any computer solver. From a simple settings file, it handle
    automatically all necessary steps to do such analysis. Furthermore,
    batman's API allows to use independantly all functionalities.
  doc_url: http://batman.readthedocs.io
  dev_url: https://batman-cerfacs.zulipchat.com

extra:
  recipe-maintainers:
    - tupui
