travis:
  secure:
    BINSTAR_TOKEN: RHPOHzAdJlZ/daNBSf97j6wApiLa4DqjA7MmJNPA5QMHbaTPa+qzttq9pywYh6g4Aq01ra7EC2fFTYwTSze+mfSWNHk4Ep3B1QAPLo5PIfACyzpWfz0Cu6AHLftUvcz+pX7nUbyPQuzYCalqwaeTr5Lcgsh+d5jn4omlpIS626WXWYIeyDSWblY2hy0Voj/68RMJ4PrnD0HyYLA6Y1eVq2pSzwWXsJZKUWs3qF7aco56ammuLq+27j0flKNXkJNiHMUGrJAZtLVMB5sRxplE1evABT+GhbP42yqGwoLfo6rYY6B/XM1FUyNZA1dYVQUHg/ZBq1vfbV0QfvukT02FlLZenwfKLLJSzkiu2zllMqY3qq7oH2M/n5yU2Moe25N+rWj8Rc9efTIM6mDBLCVv6Y0IjcuEi52RA+B2CIPxIUr0CIgZ+IdukMVQ5mRheSJuhOXNsc4VnVE7g0txuKTtAk4aNjliEC0QDFJSDWjBArOKi8PyEB3HpQFFVf/sPORlCYlPYGWmbtp50DGrmdl/WpzRsp8i963gJ39z3DURc/dblZT6KO5OM+lB4mbLC7PC5OzU2jfrZ9JpPXX3qKz3wnvgoY2P73E2tYP9o8MnyVI+tGD7Lk847eGwOA25bG1iKZORb3qKhcTtINuLzUhXnBgOBP2HzE1NsE+YqoGF9Co=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
