travis:
  secure:
    BINSTAR_TOKEN: CplgBwW8zPoONrc5faccOzXxx9rMSxiP5nBRtpMAI/H3JHGjyXRcc+555H6fiRjIpG9kPtqNdILZPshiq4NJ+/mqqyqbPfdzaOzifU+8VyEo9dhT+Gpic2poMPirreUWVuDGohwS+HS4SSCu1k8QNr+wPT4lxqQNlY86f1QuG/0z1NhDMgXIC39UG0szmWORD7nVRp01czyDYNt27Dy9aCPAcMhUow6xydf3EFyiuWbvkW+aoDmbTYP3AxJAuDw8MBewpsZREtesnMy65sDaQvfxJPJPz9+GJR59a3aYiGax1P+vpPl3N6QnXNL/1IiFSEetj+dUQUaUWvpxON3CHnr8CbtpLdCIOwyexpy5tPVODLHv6imFCAfkR7aDHnMdlUpUQLKMjdIhu5y6SVnzMQiM/Rei3NHRX5rKcbg0871bLBheEHUv/bvyBUFrF1MCdfiWmtMRpeC6oEN6JT/oIwWz6SZHiVZxYGfcFK+pv+j17tvN43a9L4FZVcP3uWa7FI0o1mH+oyA6SLq67agBfSfdNZEJm/0G6zt1bNgnV6mbuvJRv5mIMdK5WN6kSignfzYtCwp3Om7y80HzeHDfnX+TleNFNkhXzNG2nNHqip/RmIi6JF5zNor4hG9+t35I9F8JHzabtRqXGj4rnxBgS515lJ9dLxhnv15ZFLwWv4M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
