travis:
  secure:
    BINSTAR_TOKEN: faVwYEuRtWDpYywJypPZev6tuAuyWvcpvP9RUfK1bnODXUWXeZiNVLO7pjokOsJ3Quu6Kr/MgkNNdWmhbbFtRiSj2RAcSs0zon09FaT+XcauTADvbL7Chz3YrcWGyzQUe2bbu135i1MIfIbzQOQmqISQXx0+8yc5GBffUFKQk/hgE/yqkRqYZBKgICEVtr/AEpjkSY6KMnZjrM7lZ+S0XFITltvip8VfZ6Ixu6EhZ0HMfp6owicLu7F7R/BZT8SM4lkBtG9zAJkaMTDmcr8dAhFTxylj9T+HFDdUx9Dljz3SxyZpVDgqPvBHtYpJlsE4Z5lN9qN/6hjmwA080QaIiVgtklL4uKowL0AtS29efq/bl9JDrDdYO/shW1wdRlkWOZEm8jUGOud8p38I84u3+7fEIVQPn7eY8qpuZAFfCP3BxVcT7e93xtu1ruzxfHgYNn3cl0xCGYtLsbsf1fWek7G3CejSULfx8JUwti9u7tiJEFvTO3HUeFQfTeyAbuZIaX0DvQIFow/C5VyrmtXiJHHBXiJPFTnxILbj721ARVLlId/fy2Dy45gCds+aWVbnwtBq9ewKWhFeIcO72xlvnvod4S6rVN44aEr8/5R+8LAthHy9cRzBOYmrvduILHOz21KNGmb/qlTqJVkk+fCYi1tbpTHVfrwq1ParvJFXdxY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
